### ISSUE TITLE
[Bug] Scrollbar randomly jumping to the bottom

### ISSUE THREAD

**Issue by vahnag** [iteratehackerspace/react-local-chat#17]
See in action: http://d.pr/i/gTuR

The problem is in this code: https://github.com/iteratehackerspace/react-local-chat/blob/master/lib/chathistory.jsx#L16-L17

1. You should not use string refs as they are considered [legacy](https://facebook.github.io/react/docs/more-about-refs.html#the-ref-string-attribute) now.
2. You're just scrolling to the bottom every time the component is updated, which doesn't necessarily mean that a new message is added.

**Comment by fxfactorial** [comment]
@vahnag 

Thanks for the github issue. 

The reason is because a rerender happens after a setState from the socket. 

Would you like to turn your complaint into a PR, show us how to do it correctly? :)

**Comment by vahnag** [comment]
As I said in #18, it would be a good experience for the students to fix it themselves.

I would have just used [`shouldComponentUpdate()`](https://facebook.github.io/react/docs/component-specs.html#updating-shouldcomponentupdate) and checked if the last message is changed. It would also be good for UX not to scroll to the end if the user has manually scrolled up, no matter what. Just showing an indicator that a new message is arrived would be ok for that case.

But I understand that this is really in early stage, so these are just ideas to work on in the future.

**Comment by fxfactorial** [comment]
@RGA15071999 @movsessaryan @edgarkhanzadyan take note

**Comment by RGA15071999** [comment]
@vahnag scroll bug is fixed just the way you suggested.
