### ISSUE TITLE
Consider using a styleguide

### ISSUE THREAD

**Issue by vahnag** [iteratehackerspace/react-local-chat#18]
The code right now looks bad without a consistent styleguide and has a few bugs that a styleguide would have easily caught like:

* Inconsistent indentation, lack or too much of whitespace
* Lots of unnecessary uses of `let` instead of `const` and a few unused variables.
* Inconsistent file naming
* *...lots of other minor problems which will turn into bugs and unmanageable code as the project grows*

Consider using one of the many styleguides and code linting tools to improve code quality and make the app future-proof.

I'd suggest ESLint with AirBnb styleguilde, but any of them will work, just choose one and stick witg it.

**Comment by vachi** [comment]
Tho its understandable that its a learning experience, and one cant expect everything to be perfect from the get go. However adding Lintinl from the get go can help the learning process.

**Comment by fxfactorial** [comment]
@vahnag Hi, thanks for the issue. 

1) This is being some people are doing this in Atom and I'm doing it emacs, we still need to setup indentation correctly for defaults. 

2) I agree. 

3) I agree

Would you like to turn your complaints into a PR?

**Comment by vahnag** [comment]
IMHO it's important to make sure that the programmers pay attention to the code style from the beginning, it's a lot easier to do from the start than to change later on.

If you want to avoid using a linter to not complicate the code (which I don't think is an issue, but anyway), using at least [EditorConfig](http://editorconfig.org/) will help a lot.

I could have made a PR, but from my experience it's better to learn something doing it yourself from scratch (not using boilerplates, copy-pasting code etc.), so I think it would be a good experience for the beginner programmers to do themselves. Setting`eslint` up is pretty straightforward, but the programmers should learn to use it every time they start a new project.

**Comment by fxfactorial** [comment]
Agreed, they'll see this issue open and will fix it

**Comment by fxfactorial** [comment]
Added eslint, editor config
